# Generated by Django 6.0.6 on 2026-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('translator', 'Tarjimon'), ('skladchi', 'Skladchi')], default='translator', max_length=12, verbose_name='Rol'),
        ),
    ]
