# Generated by Django 6.0.6 on 2026-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_contract_order',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
