# Generated by Django 6.0.6 on 2026-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dashboard_contract_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('translator', 'Tarjimon'), ('skladchi', 'Skladchi'), ('tarozichi', 'Tarozichi')], default='translator', max_length=12, verbose_name='Rol'),
        ),
    ]
