from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views as accounts_views
from crm import views as crm_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", accounts_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", crm_views.dashboard, name="dashboard"),
    path("dashboard/contract-order/", crm_views.dashboard_contract_order,
         name="dashboard_contract_order"),
    path("audit/", crm_views.audit_list, name="audit_list"),
    path("partners/", crm_views.partner_list, name="partner_list"),
    path("partners/new/", crm_views.partner_create, name="partner_create"),
    path("partners/<int:pk>/", crm_views.partner_detail, name="partner_detail"),
    path("partners/<int:pk>/edit/", crm_views.partner_edit, name="partner_edit"),
    path("partners/<int:pk>/delete/", crm_views.partner_delete, name="partner_delete"),
    path("customers/", crm_views.customer_list, name="customer_list"),
    path("customers/new/", crm_views.customer_create, name="customer_create"),
    path("customers/quick/", crm_views.customer_quick_create, name="customer_quick_create"),
    path("customers/<int:pk>/avans/", crm_views.customer_avans, name="customer_avans"),
    path("customers/<int:pk>/edit/", crm_views.customer_edit, name="customer_edit"),
    path("customers/<int:pk>/delete/", crm_views.customer_delete, name="customer_delete"),
    path("contracts/", crm_views.contract_list, name="contract_list"),
    path("contracts/new/", crm_views.contract_create, name="contract_create"),
    path("contracts/<int:pk>/edit/", crm_views.contract_edit, name="contract_edit"),
    path("contracts/<int:pk>/delete/", crm_views.contract_delete, name="contract_delete"),
    path("supplier-payments/", crm_views.supplier_payment_list, name="supplier_payment_list"),
    path("supplier-payments/new/", crm_views.supplier_payment_create, name="supplier_payment_create"),
    path("supplier-payments/<int:pk>/edit/", crm_views.supplier_payment_edit, name="supplier_payment_edit"),
    path("supplier-payments/<int:pk>/delete/", crm_views.supplier_payment_delete, name="supplier_payment_delete"),
    path("statuses/", crm_views.status_list, name="status_list"),
    path("statuses/new/", crm_views.status_create, name="status_create"),
    path("statuses/<int:pk>/edit/", crm_views.status_edit, name="status_edit"),
    path("statuses/<int:pk>/delete/", crm_views.status_delete, name="status_delete"),
    path("statuses/<int:pk>/move/", crm_views.status_move, name="status_move"),
    path("logists/", crm_views.logist_list, name="logist_list"),
    path("logists/new/", crm_views.logist_create, name="logist_create"),
    path("logists/<int:pk>/", crm_views.logist_detail, name="logist_detail"),
    path("logists/<int:pk>/edit/", crm_views.logist_edit, name="logist_edit"),
    path("logists/<int:pk>/delete/", crm_views.logist_delete, name="logist_delete"),
    path("logist-payments/new/", crm_views.logist_payment_create, name="logist_payment_create"),
    path("logist-payments/<int:pk>/edit/", crm_views.logist_payment_edit, name="logist_payment_edit"),
    path("logist-payments/<int:pk>/delete/", crm_views.logist_payment_delete, name="logist_payment_delete"),
    path("kapital/new/", crm_views.kapital_create, name="kapital_create"),
    path("kapital/<int:pk>/edit/", crm_views.kapital_edit, name="kapital_edit"),
    path("kapital/<int:pk>/delete/", crm_views.kapital_delete, name="kapital_delete"),
    path("other-expenses/new/", crm_views.other_expense_create,
         name="other_expense_create"),
    path("other-expenses/<int:pk>/edit/", crm_views.other_expense_edit,
         name="other_expense_edit"),
    path("other-expenses/<int:pk>/delete/", crm_views.other_expense_delete,
         name="other_expense_delete"),
    path("konvertatsiya/new/", crm_views.konvertatsiya_create, name="konvertatsiya_create"),
    path("konvertatsiya/<int:pk>/edit/", crm_views.konvertatsiya_edit, name="konvertatsiya_edit"),
    path("konvertatsiya/<int:pk>/delete/", crm_views.konvertatsiya_delete, name="konvertatsiya_delete"),
    path("customs/", crm_views.customs_list, name="customs_list"),
    path("customs/new/", crm_views.customs_create, name="customs_create"),
    path("customs/loads/", crm_views.customs_loads, name="customs_loads"),
    path("customs/<int:pk>/", crm_views.customs_detail, name="customs_detail"),
    path("customs/<int:pk>/hisob.xlsx", crm_views.customs_detail_export,
         name="customs_detail_export"),
    path("customs/<int:pk>/edit/", crm_views.customs_edit, name="customs_edit"),
    path("customs/<int:pk>/delete/", crm_views.customs_delete, name="customs_delete"),
    path("customs-payments/new/", crm_views.customs_payment_create, name="customs_payment_create"),
    path("customs-payments/<int:pk>/edit/", crm_views.customs_payment_edit, name="customs_payment_edit"),
    path("customs-payments/<int:pk>/delete/", crm_views.customs_payment_delete, name="customs_payment_delete"),
    path("ombor/", crm_views.ombor, name="ombor"),
    path("shipments/", crm_views.shipment_list, name="shipment_list"),
    path("shipments/done/", crm_views.shipment_done_list, name="shipment_done_list"),
    path("shipments/new/", crm_views.shipment_create, name="shipment_create"),
    path("shipments/<int:pk>/edit/", crm_views.shipment_edit, name="shipment_edit"),
    path("shipments/<int:pk>/status/", crm_views.shipment_set_status, name="shipment_set_status"),
    path("shipments/<int:pk>/qr/", crm_views.shipment_set_qr, name="shipment_set_qr"),
    path("shipments/<int:pk>/delete/", crm_views.shipment_delete, name="shipment_delete"),
    path("shipments/<int:pk>/extend/", crm_views.shipment_extend, name="shipment_extend"),
    path("delays/<int:pk>/edit/", crm_views.shipment_delay_edit,
         name="shipment_delay_edit"),
    path("delays/<int:pk>/delete/", crm_views.shipment_delay_delete,
         name="shipment_delay_delete"),
    # The tarjimon's one write on a yuk — see crm.views.shipment_driver_edit.
    path("shipments/<int:pk>/driver/", crm_views.shipment_driver_edit, name="shipment_driver_edit"),
    path("legs/new/", crm_views.leg_create, name="leg_create"),
    path("legs/<int:pk>/edit/", crm_views.leg_edit, name="leg_edit"),
    path("legs/<int:pk>/delete/", crm_views.leg_delete, name="leg_delete"),
    path("legs/<int:pk>/move/", crm_views.leg_move, name="leg_move"),
    path("shipments/<int:pk>/", crm_views.shipment_detail, name="shipment_detail"),
    path("expenses/new/", crm_views.expense_create, name="expense_create"),
    path("expenses/<int:pk>/edit/", crm_views.expense_edit, name="expense_edit"),
    path("expenses/<int:pk>/delete/", crm_views.expense_delete, name="expense_delete"),
    path("ombor/lot/<int:pk>/", crm_views.lot_detail, name="lot_detail"),
    # `path` rather than `str`: a marka is free text on the kelishuv row and may
    # carry a slash, which `str` would refuse to match.
    path("ombor/marka/<path:brand>/", crm_views.brand_detail, name="brand_detail"),
    path("sales/", crm_views.sale_list, name="sale_list"),
    path("sales/new/", crm_views.sale_create, name="sale_create"),
    path("sales/<int:pk>/edit/", crm_views.sale_edit, name="sale_edit"),
    path("sales/<int:pk>/shift-preview/", crm_views.sale_shift_preview,
         name="sale_shift_preview"),
    path("sales/<int:pk>/delete/", crm_views.sale_delete, name="sale_delete"),
    path("sales/<int:pk>/", crm_views.sale_detail, name="sale_detail"),
    path("reservations/", crm_views.reservation_list, name="reservation_list"),
    path("reservations/new/", crm_views.reservation_create, name="reservation_create"),
    path("reservations/<int:pk>/edit/", crm_views.reservation_edit, name="reservation_edit"),
    path("reservations/<int:pk>/delete/", crm_views.reservation_delete, name="reservation_delete"),
    path("reservations/<int:pk>/cancel/", crm_views.reservation_cancel, name="reservation_cancel"),
    path("reservations/<int:pk>/close/", crm_views.reservation_close, name="reservation_close"),
    path("returns/", crm_views.return_list, name="return_list"),
    path("returns/new/", crm_views.return_create, name="return_create"),
    # The rows for one mijoz, fetched by the modal when the mijoz select changes.
    path("returns/rows/", crm_views.return_rows, name="return_rows"),
    # `batch` before the int route so the word cannot be read as a pk.
    path("returns/batch/<int:pk>/edit/", crm_views.return_batch_edit,
         name="return_batch_edit"),
    path("returns/batch/<int:pk>/delete/", crm_views.return_batch_delete,
         name="return_batch_delete"),
    path("return-settlements/<int:pk>/pay/", crm_views.return_settlement_pay,
         name="return_settlement_pay"),
    path("return-settlements/<int:pk>/edit/", crm_views.return_settlement_edit,
         name="return_settlement_edit"),
    path("return-settlements/<int:pk>/to-advance/",
         crm_views.return_settlement_to_advance, name="return_settlement_to_advance"),
    path("returns/export.xlsx", crm_views.return_list_export, name="return_list_export"),
    path("customer-payments/", crm_views.customer_payment_list, name="customer_payment_list"),
    path("customer-payments/new/", crm_views.customer_payment_create, name="customer_payment_create"),
    path("customer-payments/<int:pk>/", crm_views.customer_payment_detail, name="customer_payment_detail"),
    path("customer-payments/<int:pk>/edit/", crm_views.customer_payment_edit, name="customer_payment_edit"),
    path("customer-payments/<int:pk>/delete/", crm_views.customer_payment_delete, name="customer_payment_delete"),
    path("debts/", crm_views.debt_list, name="debt_list"),
    path("debts/<int:pk>/", crm_views.debt_customer, name="debt_customer"),
    path("debts/<int:pk>/tarix.xlsx", crm_views.debt_customer_history_export,
         name="debt_customer_history_export"),
    path("kassa/", crm_views.kassa, name="kassa"),
    path("reports/", crm_views.reports, name="reports"),
    path("reports/export/contracts.xlsx", crm_views.export_contracts, name="export_contracts"),
    path("reports/export/supplier-payments.xlsx", crm_views.export_supplier_payments,
         name="export_supplier_payments"),
    path("reports/export/shipments.xlsx", crm_views.export_shipments, name="export_shipments"),
    path("reports/export/sales.xlsx", crm_views.export_sales, name="export_sales"),
    path("reports/export/debts.xlsx", crm_views.export_debts, name="export_debts"),
    # The Excel button on each ro'yxat. A separate URL per list rather than the
    # hisobotlar ones with different params: each goes through its OWN page's filter
    # helper, so the file holds exactly the rows that were on the screen.
    path("contracts/export.xlsx", crm_views.contract_list_export, name="contract_list_export"),
    path("shipments/export.xlsx", crm_views.shipment_list_export, name="shipment_list_export"),
    path("sales/export.xlsx", crm_views.sale_list_export, name="sale_list_export"),
    path("customer-payments/export.xlsx", crm_views.customer_payment_list_export,
         name="customer_payment_list_export"),
    path("supplier-payments/export.xlsx", crm_views.supplier_payment_list_export,
         name="supplier_payment_list_export"),
    path("debts/export.xlsx", crm_views.debt_list_export, name="debt_list_export"),
    path("ombor/export.xlsx", crm_views.ombor_export, name="ombor_export"),
    path("audit/export.xlsx", crm_views.audit_list_export, name="audit_list_export"),
    path("kassa/export.xlsx", crm_views.kassa_export, name="kassa_export"),
    path("users/", accounts_views.user_list, name="user_list"),
    path("users/new/", accounts_views.user_create, name="user_create"),
    path("users/<int:pk>/edit/", accounts_views.user_edit, name="user_edit"),
]
