# Generated by Django 6.0.6 on 2026-07-18 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Granula markasi')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Kelishilgan kg')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='1 kg narxi (USD)')),
                ('created', models.DateField(default=django.utils.timezone.localdate, verbose_name='Kelishuv sanasi')),
                ('deadline', models.DateField(verbose_name='Yetkazish muddati')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim ochdi')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.partner', verbose_name='Hamkor')),
            ],
            options={
                'verbose_name': 'Kelishuv',
                'verbose_name_plural': 'Kelishuvlar',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
