# Generated by Django 6.0.6 on 2026-07-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_supplierpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_arrival', models.BooleanField(default=False, verbose_name='Omborga kelish holati')),
            ],
            options={
                'verbose_name': 'Yuk holati',
                'verbose_name_plural': 'Yuk holatlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
