# Generated by Django 6.0.6 on 2026-07-18 15:06

from django.db import migrations

NAMES = ["Tayyorlanmoqda", "Yuklanmoqda", "Yo'lda", "Chegarada", "Bojxona",
         "Omborga yetib keldi"]


def seed(apps, schema_editor):
    ShipmentStatus = apps.get_model("crm", "ShipmentStatus")
    for i, name in enumerate(NAMES, start=1):
        ShipmentStatus.objects.get_or_create(
            name=name, defaults={"order": i, "is_arrival": name == NAMES[-1]})


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_shipmentstatus'),
    ]

    operations = [
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
