# Generated by Django 6.0.6 on 2026-07-18 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_seed_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Yuborilgan kg')),
                ('sent', models.DateField(blank=True, null=True, verbose_name="Jo'natilgan sana")),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Taxminiy kelish')),
                ('arrived', models.DateField(blank=True, null=True, verbose_name='Yetib kelgan sana')),
                ('transport', models.CharField(blank=True, max_length=50, verbose_name='Transport raqami')),
                ('container', models.CharField(blank=True, max_length=50, verbose_name='Konteyner raqami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='crm.contract', verbose_name='Kelishuv')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='crm.shipmentstatus', verbose_name='Holat')),
            ],
            options={
                'verbose_name': 'Yuk',
                'verbose_name_plural': 'Yuklar',
                'ordering': ['-created_at'],
            },
        ),
    ]
