# Generated by Django 6.0.6 on 2026-07-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_eta', models.DateField(null=True, verbose_name='Avvalgi sana')),
                ('new_eta', models.DateField(verbose_name='Yangi sana')),
                ('reason', models.CharField(max_length=255, verbose_name='Kechikish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_delays', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='crm.shipment', verbose_name='Yuk')),
            ],
            options={
                'verbose_name': 'Yuk kechikishi',
                'verbose_name_plural': 'Yuk kechikishlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
