# Generated by Django 6.0.6 on 2026-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_shipmentexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['name'],
            },
        ),
    ]
