# Generated by Django 6.0.6 on 2026-07-18 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sotilgan kg')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='1 kg sotuv narxi (USD)')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='1 kg tan narxi (USD)')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('debt_deadline', models.DateField(blank=True, null=True, verbose_name="To'lov muddati")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='crm.customer', verbose_name='Mijoz')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='crm.shipment', verbose_name='Lot (yuk)')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
