# Generated by Django 6.0.6 on 2026-07-18 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('currency', models.CharField(choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='usd', max_length=3, verbose_name='Valyuta')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name="Dollar kursi (1$ = so'm)")),
                ('amount_original', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Asl summa (valyutada)')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='transfer', max_length=8, verbose_name="To'lov usuli")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='crm.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': "Mijoz to'lovi",
                'verbose_name_plural': "Mijoz to'lovlari",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='crm.customerpayment', verbose_name="To'lov")),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='crm.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': "To'lov taqsimoti",
                'verbose_name_plural': "To'lov taqsimotlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
