# Generated by Django 6.0.6 on 2026-07-18 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customerpayment_paymentallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', "Qo'shildi"), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('status', "Holat o'zgardi"), ('payment', "To'lov"), ('return', 'Qaytarish')], max_length=10, verbose_name='Amal'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qaytarilgan kg')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='1 kg narxi (USD)')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('restock', models.BooleanField(default=True, verbose_name='Omborga qaytarilsinmi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='crm.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Qaytarish',
                'verbose_name_plural': 'Qaytarishlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
