# Generated by Django 6.0.6 on 2026-07-18 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_auditlog_action_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Bron qilingan kg')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='1 kg narxi (USD)')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('converted', 'Sotuvga aylandi'), ('cancelled', 'Bekor qilindi')], default='active', max_length=10, verbose_name='Holat')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.customer', verbose_name='Mijoz')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.shipment', verbose_name='Lot (yuk)')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earmarked_payments', to='crm.reservation', verbose_name='Bron uchun'),
        ),
        migrations.AddField(
            model_name='sale',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.reservation', verbose_name='Bron'),
        ),
    ]
