# Generated by Django 6.0.6 on 2026-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_reservation_customerpayment_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, max_length=120, verbose_name='Qayerga (yetkazish joyi)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, max_length=120, verbose_name="Qayerdan (jo'natilish joyi)"),
        ),
    ]
