# Generated by Django 6.0.6 on 2026-07-19 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_shipment_destination_shipment_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('from_location', models.CharField(max_length=120, verbose_name='Qayerdan')),
                ('to_location', models.CharField(max_length=120, verbose_name='Qayerga')),
                ('transport', models.CharField(blank=True, max_length=50, verbose_name='Haydovchi / transport')),
                ('container', models.CharField(blank=True, max_length=50, verbose_name='Konteyner')),
                ('departed', models.DateField(blank=True, null=True, verbose_name="Jo'natilgan sana")),
                ('arrived', models.DateField(blank=True, null=True, verbose_name='Yetib kelgan sana')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_legs', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='crm.shipment', verbose_name='Yuk')),
            ],
            options={
                'verbose_name': "Yo'nalish bosqichi",
                'verbose_name_plural': "Yo'nalish bosqichlari",
                'ordering': ['order', 'id'],
            },
        ),
    ]
