# Generated by Django 6.0.6 on 2026-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_shipmentleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Bo'sh qoldirilsa kelishuv narxi olinadi", max_digits=14, null=True, verbose_name='1 kg narxi (USD)'),
        ),
    ]
