# Generated by Django 6.0.6 on 2026-07-23 05:48

from django.db import migrations, models


def fill_route(apps, schema_editor):
    """Loads entered before the route became a constant left it blank; every run is
    Eron → O'zbekiston, so filling them in states what was already true."""
    Shipment = apps.get_model("crm", "Shipment")
    Shipment.objects.filter(origin="").update(origin="Eron")
    Shipment.objects.filter(destination="").update(destination="O'zbekiston")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_shipment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, default="O'zbekiston", max_length=120, verbose_name='Qayerga (yetkazish joyi)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, default='Eron', max_length=120, verbose_name="Qayerdan (jo'natilish joyi)"),
        ),
        migrations.RunPython(fill_route, migrations.RunPython.noop),
    ]
