# Generated by Django 6.0.6 on 2026-07-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_shipment_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deadline',
        ),
    ]
