# Generated by Django 6.0.6 on 2026-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_drop_contract_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='planned_trucks',
            field=models.PositiveIntegerField(blank=True, help_text="Kelishuv bo'yicha rejalashtirilgan mashinalar soni", null=True, verbose_name='Nechta mashina'),
        ),
    ]
