# Generated by Django 6.0.6 on 2026-07-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_contract_planned_trucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cost_price',
        ),
    ]
