# Generated by Django 6.0.6 on 2026-07-25 14:31
#
# Tannarx went fully live (goods + freight + vositachi, computed on the fly), so a
# sale no longer freezes its cost. Rather than DROP the old snapshots — real recorded
# profit history — we keep them: rename cost_price -> cost_price_snapshot (read-only
# audit trail) and make it nullable for sales created after the switch.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_contract_planned_trucks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cost_price',
            new_name='cost_price_snapshot',
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost_price_snapshot',
            field=models.DecimalField(
                "1 kg tan narxi (tarixiy)", max_digits=14, decimal_places=4,
                null=True, blank=True),
        ),
    ]
