# Generated by Django 6.0.6 on 2026-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_dual_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentexpense',
            name='category',
            field=models.CharField(choices=[('customs', 'Bojxona'), ('declarant', 'Deklarant'), ('transport', 'Transport'), ('loader', 'Gruzchi'), ('road', "Yo'l xarajati"), ('cert', 'Sertifikat'), ('other', 'Boshqa')], default='other', max_length=10, verbose_name='Turkum'),
        ),
    ]
