# Generated by Django 6.0.6 on 2026-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_paymentallocation_amount_uzs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='fee_bearer',
            field=models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi"),
        ),
        migrations.AddField(
            model_name='logistpayment',
            name='fee_bearer',
            field=models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi"),
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='fee_bearer',
            field=models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi"),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='fee_bearer',
            field=models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi"),
        ),
    ]
