# Generated by Django 6.0.6 on 2026-08-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_customerpayment_fee_bearer_logistpayment_fee_bearer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='target_currency',
            field=models.CharField(blank=True, choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='', help_text="Mijozning qaysi valyutadagi qarzi to'lanmoqda", max_length=3, verbose_name='Qaysi qarzga'),
        ),
    ]
