# Generated by Django 6.0.6 on 2026-08-07 22:34

import crm.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_customerpayment_target_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bojxonachi',
                'verbose_name_plural': 'Bojxonachilar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='customs_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='crm.customsagent', verbose_name="Bojxonachi to'ladi"),
        ),
        migrations.CreateModel(
            name='CustomsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='usd', max_length=3, verbose_name='Valyuta')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('12000'), max_digits=12, verbose_name="Dollar kursi (1$ = so'm)")),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Faqat perechisleniya uchun; naqd va kartada e'tiborga olinmaydi", max_digits=5, verbose_name='Perechisleniya foizi (%)')),
                ('fee_bearer', models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi")),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.customsagent', verbose_name='Bojxonachi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_payments', to='crm.shipment', verbose_name='Qaysi yuk uchun')),
            ],
            options={
                'verbose_name': "Bojxonaga to'lov",
                'verbose_name_plural': "Bojxonaga to'lovlar",
                'ordering': ['-date', '-created_at'],
            },
            bases=(crm.models.HeldFloat, models.Model),
        ),
    ]
