# Generated by Django 6.0.6 on 2026-08-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_customerpayment_target_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('converted', 'Sotuvga aylandi'), ('closed', 'Tugatildi'), ('cancelled', 'Bekor qilindi')], default='active', max_length=10, verbose_name='Holat'),
        ),
    ]
