# Generated by Django 6.0.6 on 2026-08-07 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_customsagent_shipmentexpense_customs_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shipmentexpense',
            constraint=models.CheckConstraint(condition=models.Q(('logist__isnull', True), ('customs_agent__isnull', True), _connector='OR'), name='expense_has_one_payer'),
        ),
    ]
