# Generated by Django 6.0.6 on 2026-08-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_alter_reservation_status'),
        ('crm', '0038_shipmentexpense_expense_has_one_payer'),
    ]

    operations = [
    ]
