# Generated by Django 6.0.6 on 2026-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_merge_customs_and_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='qr_date',
            field=models.DateField(blank=True, help_text="QR kod olgan haydovchi tezroq yetib keladi. Bu yukka berilmasa — bo'sh qoldiring.", null=True, verbose_name='QR kod beriladigan kun'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='qr_given',
            field=models.DateField(blank=True, null=True, verbose_name='QR kod berilgan sana'),
        ),
    ]
