# Generated by Django 6.0.6 on 2026-08-11 09:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_merge_customs_and_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='usd', max_length=3, verbose_name='Valyuta')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('12000'), max_digits=12, verbose_name="Dollar kursi (1$ = so'm)")),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Faqat perechisleniya uchun; naqd va kartada e'tiborga olinmaydi", max_digits=5, verbose_name='Perechisleniya foizi (%)')),
                ('fee_bearer', models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi")),
                ('kind', models.CharField(choices=[('in', 'Kiritildi'), ('out', 'Olindi')], default='in', max_length=3, verbose_name="Yo'nalish")),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='transfer', max_length=8, verbose_name="To'lov usuli")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kapital_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
            ],
            options={
                'verbose_name': 'Kapital',
                'verbose_name_plural': 'Kapital',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
