# Generated by Django 6.0.6 on 2026-08-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_shipment_qr_date_shipment_qr_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Sotuv guruhi'),
        ),
    ]
