# Generated by Django 6.0.6 on 2026-08-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_backfill_sale_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Kg')),
                ('pinned', models.BooleanField(default=False, verbose_name="Lot qo'lda tanlangan")),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lots', to='crm.shipmentline', verbose_name='Lot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='crm.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv loti',
                'verbose_name_plural': 'Sotuv lotlari',
                'ordering': ['sale_id', 'id'],
            },
        ),
    ]
