# Generated by Django 6.0.6 on 2026-08-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_kapital'),
        ('crm', '0042_backfill_sale_group'),
    ]

    operations = [
    ]
