# Generated by Django 6.0.6 on 2026-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_merge_0040_kapital_0042_backfill_sale_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi"),
        ),
        migrations.AddField(
            model_name='customspayment',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi"),
        ),
        migrations.AddField(
            model_name='kapital',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi"),
        ),
        migrations.AddField(
            model_name='logistpayment',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi"),
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi"),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi"),
        ),
    ]
