# Generated by Django 6.0.6 on 2026-08-15 18:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_customerpayment_group_customspayment_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konvertatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('from_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name='Qayerdan')),
                ('from_currency', models.CharField(choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='uzs', max_length=3, verbose_name='Qaysi valyutadan')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Chiqdi')),
                ('to_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name='Qayerga')),
                ('to_currency', models.CharField(choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='usd', max_length=3, verbose_name='Qaysi valyutaga')),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tushdi')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('12000'), max_digits=12, verbose_name="Dollar kursi (1$ = so'm)")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='konvertatsiyalar', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
            ],
            options={
                'verbose_name': 'Konvertatsiya',
                'verbose_name_plural': 'Konvertatsiyalar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
