# Generated by Django 6.0.6 on 2026-08-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_konvertatsiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli"),
        ),
    ]
