# Generated by Django 6.0.6 on 2026-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_alter_customerpayment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapital',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli"),
        ),
    ]
