# Generated by Django 6.0.6 on 2026-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_trucks_per_product_and_payment_product'),
        ('crm', '0047_alter_kapital_method'),
    ]

    operations = [
    ]
