# Generated by Django 6.0.6 on 2026-08-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_merge_20260816_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Summa (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_allocations', to='crm.contractline', verbose_name='Mahsulot')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='crm.supplierpayment', verbose_name="To'lov")),
            ],
            options={
                'verbose_name': "Hamkor to'lovi taqsimoti",
                'verbose_name_plural': "Hamkor to'lovi taqsimotlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
