# Generated by Django 6.0.6 on 2026-08-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_otherexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customs_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_shipments', to='crm.customsagent', verbose_name='Bojxonachi'),
        ),
    ]
