# Generated by Django 6.0.6 on 2026-08-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_returnbatch_return_batch_returnsettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Summa (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_allocations', to='crm.customerpayment', verbose_name="Mijoz to'lovi")),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='crm.returnsettlement', verbose_name='Vazvrat hisob-kitobi')),
            ],
            options={
                'verbose_name': 'Vazvrat taqsimoti',
                'verbose_name_plural': 'Vazvrat taqsimotlari',
            },
        ),
    ]
