# Generated by Django 6.0.6 on 2026-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_refundallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='to_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qarzdan yopildi (USD)'),
        ),
        migrations.AddField(
            model_name='return',
            name='to_debt_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Qarzdan yopildi (so'm)"),
        ),
    ]
