# Generated by Django 6.0.6 on 2026-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_backfill_return_to_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='to_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Qarzdan ayirildi (USD)'),
        ),
        migrations.AlterField(
            model_name='return',
            name='to_debt_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Qarzdan ayirildi (so'm)"),
        ),
    ]
