# Generated by Django 6.0.6 on 2026-08-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_shipment_customs_agent'),
        ('crm', '0058_absorb_unplaceable_payment_tails'),
    ]

    operations = [
    ]
