# Generated by Django 6.0.6 on 2026-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_merge_20260822_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reys',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Reys'),
        ),
    ]
