# Generated by Django 6.0.6 on 2026-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_shipment_lines_inherit_kelishuv_narx'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_birja',
            field=models.BooleanField(default=False, editable=False, verbose_name='Birja'),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='scope',
            field=models.CharField(choices=[('hamkor', 'Hamkor yuklari'), ('birja', 'Birja yuklari'), ('umumiy', 'Ikkalasi ham')], default='hamkor', max_length=10, verbose_name='Qaysi yuklar uchun'),
        ),
        migrations.AlterField(
            model_name='shipmentstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AddConstraint(
            model_name='shipmentstatus',
            constraint=models.UniqueConstraint(fields=('name', 'scope'), name='unique_status_name_per_scope'),
        ),
    ]
