# Generated by Django 6.0.6 on 2026-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_seed_birja_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentexpense',
            name='rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='1 kg uchun'),
        ),
    ]
