# Generated by Django 6.0.6 on 2026-09-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_shipmentexpense_rate_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='transport_rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Yuk omborga yetib kelganda shu narxda transport xarajati o'zi yoziladi. Bo'sh — bunday kelishuv yo'q.", max_digits=14, null=True, verbose_name='Transport · 1 kg uchun'),
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='is_auto_transport',
            field=models.BooleanField(default=False, editable=False, verbose_name='Kelishuvdan'),
        ),
    ]
