# Generated by Django 6.0.6 on 2026-09-02 12:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_contract_transport_rate_per_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'Dollar'), ('uzs', "So'm")], default='usd', max_length=3, verbose_name='Valyuta')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('12000'), max_digits=12, verbose_name="Dollar kursi (1$ = so'm)")),
                ('group', models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name="To'lov guruhi")),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Faqat perechisleniya uchun; naqd va kartada e'tiborga olinmaydi", max_digits=5, verbose_name='Perechisleniya foizi (%)')),
                ('fee_bearer', models.CharField(blank=True, choices=[('company', 'Kompaniyadan ushlansin'), ('counterparty', 'Qarshi tomondan ushlansin')], default='', max_length=12, verbose_name="Komissiyani kim ko'taradi")),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('category', models.CharField(choices=[('broker', 'Broker'), ('other', 'Boshqa')], default='broker', max_length=10, verbose_name='Turkum')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Foiz (%)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa (USD)')),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='crm.contract', verbose_name='Kelishuv')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
            ],
            options={
                'verbose_name': 'Kelishuv xarajati',
                'verbose_name_plural': 'Kelishuv xarajatlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
