# Generated by Django 6.0.6 on 2026-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_contractexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractexpense',
            name='category',
            field=models.CharField(choices=[('broker', 'Broker'), ('transport', 'Transport (1 kg uchun)'), ('other', 'Boshqa')], default='broker', max_length=10, verbose_name='Turkum'),
        ),
    ]
