# Generated by Django 6.0.6 on 2026-09-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_alter_contractexpense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prefill_last_price',
            field=models.BooleanField(default=False, help_text="Sotuv formasi shu mijozga shu marka oxirgi marta qanday narxda sotilgan bo'lsa, o'sha narx bilan ochiladi. Narxni qo'lda o'zgartirish mumkin.", verbose_name='Narx oxirgi sotuvdan olinsin'),
        ),
    ]
