# Generated by Django 6.0.6 on 2026-09-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_customer_prefill_last_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prefill_last_price',
        ),
    ]
