# Generated by Django 6.0.6 on 2026-09-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_markalar_kirilcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='position',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Kun ichidagi tartib'),
        ),
    ]
