# Generated by Django 6.0.6 on 2026-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_sale_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='closed_short',
            field=models.BooleanField(default=False, editable=False, verbose_name='Kam qoldiq bilan yopilgan'),
        ),
    ]
