# Generated by Django 6.0.6 on 2026-09-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_bron_served_by_edit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_local',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mahalliy xarid'),
        ),
        migrations.CreateModel(
            name='LocalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=200, verbose_name='Sotuvchi')),
                ('seller_phone', models.CharField(blank=True, max_length=30, verbose_name='Sotuvchi telefoni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_purchase', to='crm.contract', verbose_name='Kelishuv')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_purchase', to='crm.shipment', verbose_name='Yuk')),
            ],
            options={
                'verbose_name': 'Mahalliy xarid',
                'verbose_name_plural': 'Mahalliy xaridlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
