# Generated by Django 6.0.6 on 2026-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_local_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistpayment',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Vositachisiz to'lov uchun bo'sh qoldiring", max_digits=5, verbose_name='Vositachi foizi (%)'),
        ),
    ]
