# Generated by Django 6.0.6 on 2026-09-23 14:47

import django.db.models.deletion
from django.db import migrations, models


def link_spot_payments(apps, schema_editor):
    """Point every existing mahalliy xarid at the to'lov its "Hozir to'landi" wrote.

    Before this field the only mark that to'lov carried was its izoh, so that is what
    is matched — the earliest one on the kelishuv. A purchase with none was nasiya."""
    LocalPurchase = apps.get_model("crm", "LocalPurchase")
    SupplierPayment = apps.get_model("crm", "SupplierPayment")
    for purchase in LocalPurchase.objects.all():
        payment = (SupplierPayment.objects
                   .filter(contract_id=purchase.contract_id, note="Xarid paytida to'landi")
                   .order_by("created_at", "pk").first())
        if payment:
            purchase.spot_payment = payment
            purchase.save(update_fields=["spot_payment"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_shipment_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchase',
            name='spot_payment',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_purchase', to='crm.supplierpayment', verbose_name="Xarid paytidagi to'lov"),
        ),
        migrations.RunPython(link_spot_payments, migrations.RunPython.noop),
    ]
