# Generated by Django 6.0.6 on 2026-10-09 05:51

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_reservation_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('device_id', models.CharField(default=crm.models._scale_device_id, editable=False, max_length=40, unique=True, verbose_name='Device ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('online', models.BooleanField(default=False, editable=False, verbose_name='Ulangan')),
                ('peer', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Manzil')),
                ('last_raw', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Oxirgi qator')),
                ('last_kg', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=12, null=True, verbose_name='Oxirgi vazn')),
                ('last_stable', models.BooleanField(default=False, editable=False, verbose_name='Barqaror')),
                ('last_seen', models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Oxirgi ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarozi',
                'verbose_name_plural': 'Tarozilar',
                'ordering': ['name', 'id'],
            },
        ),
    ]
