# Generated by Django 6.0.6 on 2026-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='require_id',
            field=models.BooleanField(default=True, verbose_name='Device ID talab qilinadi'),
        ),
    ]
